apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mpi-nodes
  labels:
    app: mpi-nodes
spec:
  replicas: 3
#  selector:
#    matchLabels:
#      app: mpi-header
  template:
    metadata:
      labels:
        app: mpi-nodes
    spec:
      containers:
      - image: typhoon1986/paddle-openmpi
        name : mpi-header
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 2Gi
        ports:
        - containerPort: 22
  
